//import './globals.css'
'use client'
import 'bootstrap/dist/css/bootstrap.min.css';
import { Inter } from 'next/font/google'
import AppHeader from '@/app/components/app.header'
import Appfooter from '@/app/components/app.footer'
import Container from 'react-bootstrap/Container'

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppHeader/>
        <Container>
        {children}
        </Container>
       
        <Appfooter/>
      </body>
    </html>
  )
}
